language: scala
scala:
  - 2.10.4
  - 2.11.2
jdk:
  - openjdk7
  - oraclejdk7
script: sbt clean test 
notifications:
  email:
    recipients:
    - konstantin.spitsyn@gmail.com
    - plokhotnyuk@gmail.com